question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "Bananas are berries, but strawberries are not.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Honey never spoils. Archaeologists found 3000-year-old honey that was still edible.", "answer": "True"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer due to heat expansion.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "Nintendo was founded in 1889.", "answer": "True"},
    {"text": "Humans share 60% of their DNA with bananas.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "Venus is the only planet that spins clockwise.", "answer": "True"},
    {"text": "A jiffy is an actual unit of time — 1/100th of a second.", "answer": "True"},
    {"text": "There are more trees on Earth than stars in the Milky Way.", "answer": "True"},
    {"text": "Oxford University is older than the Aztec Empire.", "answer": "True"},
]